# Aggregator Configuration
aggregator:
  host: "localhost"
  port: 50051
  max_participants: 10
  min_participants: 2
  
# Security Configuration
security:
  paillier:
    key_size: 2048
    threshold: 2  # Minimum number of parties required for decryption
  
# Differential Privacy Configuration
differential_privacy:
  epsilon: 1.0  # Privacy budget
  delta: 1e-5   # Failure probability
  noise_mechanism: "gaussian"  # or "laplace"
  clipping_norm: 1.0
  
# Model Configuration
model:
  type: "decision_tree"  # or "cnn", "svm"
  rounds: 10  # Number of federated learning rounds
  
# Communication
communication:
  timeout: 30  # seconds
  max_retries: 3
  
# Logging
logging:
  level: "INFO"
  file: "logs/aggregator.log"
