# Data Party 3 Configuration
party:
  id: 3
  host: "0.0.0.0"
  port: 50052
  
# Aggregator Connection
aggregator:
  host: "aggregator"
  port: 50051
  
# Dataset Configuration
dataset:
  name: "iris"
  path: "data/party_1/iris_party_1.csv"  # Using the existing data file
  train_size: 0.8
  random_seed: 44
  partition_index: 2
  
# Local Training Configuration
training:
  epochs: 5
  batch_size: 32
  learning_rate: 0.01
  
# Model Configuration
model:
  type: "decision_tree"
  parameters:
    max_depth: 5
    min_samples_split: 2
    
# Security Configuration
security:
  encrypt_updates: true
  
# Logging
logging:
  level: "INFO"
  file: "logs/party_3.log"
